jmiller:
    ECMWF:
        dir_name: DY
        syntrack_prefix: ""
        num_ens: 52
        max_step: 360
        temporal_resolution: 6
    NCEP:
        dir_name: GEFS
        syntrack_prefix: gefs_
        num_ens: 32
        max_step: 384
        temporal_resolution: 6
    paths:
        syntrack:
            al: /Users/jmiller/Work/data
        invest:
            al: /Users/jmiller/Work/data/INV/
        staging_dir: /Users/jmiller/Dropbox/git/projects/tcdb/data/staging
        local_mysql_dir: /Users/jmiller/Dropbox/git/projects/tcdb/data/mysql
        static_data_dir: /Users/jmiller/Dropbox/git/projects/tcdb/data/static