INSERT INTO models (long_name, short_name)
VALUES
    ("Combined ARQ Position", "CARQ"),
    ("NHC official forecast", "OFCL"),
    ("NHC official forecast (Interpolated 06 hours)", "OFCI"),
    ("NHC official forecast (Interpolated 12 hours)", "OFC2"),
    ("NHC provisional forecast", "OFCP"),
    ("NHC provisional forecast (Interpolated 06 hours)", "OFPI"),
    ("NHC provisional forecast (Interpolated 12 hours)", "OFP2"),
    ("Original NHC official forecast (retained when special advisory issued)", "OFCO"),
    ("Combination of CLP5 and Decay-SHIFOR run on operational inputs", "OCD5"),
    ("Combination of CLP5 and Decay-SHIFOR run on operational inputs", "BCD5"),
    ("WPC official forecast", "OHPC"),
    ("OPC official forecast", "OOPC"),
    ("JTWC official forecast", "JTWC"),
    ("JTWC official forecast (Interpolated 06 hours)", "JTWI"),
    ("Extrapolation using past 12-hr motion", "XTRP"),
    ("CLImatology-PERsistence model 3-day", "CLIP"),
    ("CLImatology-PERsistence model 5-day", "CLP5"),
    ("Trajectory CLIPER model 7-day", "TCLP"),
    ("LBAR", "LBAR"),
    ("FSU Superensemble", "FSSE"),
    ("HWRF model", "HWRF"),
    ("HWRF model (Interpolated 06 hrs) - variable offset intensity", "HWFI"),
    ("HWRF model (Interpolated 12 hrs) - variable offset intensity", "HWF2"),
    ("HWRF model (Interpolated 06 hrs) - variable offset radii", "HHFI"),
    ("HWRF model (Interpolated 12 hrs) - variable offset radii", "HHF2"),
    ("HWRF w/ ECMWF fields model", "HWFE"),
    ("HWRF w/ ECMWF fields model (Interpolated 06 hours)", "HWEI"),
    ("HWRF w/ ECMWF fields model (Interpolated 12 hours)", "HWE2"),
    ("HWRF model [2013 version]", "HW3F"),
    ("HWRF model [2013 version] (Interpolated 06 hours)", "HW3I"),
    ("HWRF model [2013 version] (Interpolated 12 hours)", "HW32"),
    ("HMON model", "HMON"),
    ("HMON model (Interpolated 06 hours) - variable offset intensity", "HMNI"),
    ("HMON model (Interpolated 12 hours) - variable offset intensity", "HMN2"),
    ("HMON model (Interpolated 06 hours) - variable offset radii", "HHNI"),
    ("HMON model (Interpolated 12 hours) - variable offset radii", "HHN2"),
    ("Coupled Hurricane Intensity Prediction System", "CHIP"),
    ("Coupled Hurricane Intensity Prediction System (Interpolated 06 hours)", "CHPI"),
    ("Coupled Hurricane Intensity Prediction System (Interpolated 12 hours)", "CHP2"),
    ("HAFS-A - Stand Alone Regional", "HAFA"),
    ("HAFS-A (Interpolated 06 hours) - variable offset intensity", "HFAI"),
    ("HAFS-A (Interpolated 12 hours) - variable offset intensity", "HFA2"),
    ("HAFS-B - Global with Static Nest", "HAFB"),
    ("HAFS-B (Interpolated 06 hours) - variable offset intensity", "HFBI"),
    ("HAFS-B (Interpolated 12 hours) - variable offset intensity", "HFB2"),
    ("HAFS-SAR with ESG Grid", "HAFJ"),
    ("HAFS-SAR (Interpolated 06 hours) - variable offset intensity", "HFJI"),
    ("HAFS-SAR (Interpolated 12 hours) - variable offset intensity", "HFJ2"),
    ("Basin-Scale HWRF", "HB20"),
    ("Basin-Scale HWRF (Interpolated 06 hours) - variable offset intensity", "HB0I"),
    ("Basin-Scale HWRF (Interpolated 12 hours) - variable offset intensity", "HB02"),
    ("GFDL model", "GFDL"),
    ("GFDL model (Interpolated 06 hours)", "GFDI"),
    ("GFDL model (Interpolated 12 hours)", "GFD2"),
    ("Parallel version of GFDL", "GFD5"),
    ("Parallel version of GFDL (Interpolated 06 hours)", "GF5I"),
    ("Parallel version of GFDL (Interpolated 12 hours)", "GF52"),
    ("GFDL w/ ECMWF fields model", "GFDE"),
    ("GFDL w/ ECMWF fields model (Interpolated 06 hours)", "GFEI"),
    ("GFDL w/ ECMWF fields model (Interpolated 12 hours)", "GFE2"),
    ("GFDL 06-h interpolated model using variable intensity offset", "GHMI"),
    ("GFDL 12-h interpolated model using variable intensity offset", "GHM2"),
    ("GFDL using [NCEP tracker]", "GFDT"),
    ("GFDL using [NCEP tracker] (Interpolated 06 hours)", "GFTI"),
    ("GFDL using [NCEP tracker] (Interpolated 12 hours)", "GFT2"),
    ("Navy GFDL model", "GFDN"),
    ("Navy GFDL model (Interpolated 06 hours)", "GFNI"),
    ("Navy GFDL model (Interpolated 12 hours)", "GFN2"),
    ("NAM model", "NAM"),
    ("NAM model (Interpolated 06 hours)", "NAMI"),
    ("NAM model (Interpolated 12 hours)", "NAM2"),
    ("COAMPS Carib/E Pacific grid", "COCE"),
    ("COAMPS Carib/E Pacific grid (Interpolated 06 hours)", "COEI"),
    ("COAMPS Carib/E Pacific grid (Interpolated 12 hours)", "COE2"),
    ("COAMPS Atlantic grid", "COAL"),
    ("COAMPS Atlantic grid (Interpolated 06 hours)", "COAI"),
    ("COAMPS Atlantic grid (Interpolated 12 hours)", "COA2"),
    ("Legacy GFS Model", "GFSL"),
    ("Legacy GFS Model (Interpolated 06 hours)", "GFLI"),
    ("Legacy GFS Model (Interpolated 12 hours)", "GFL2"),
    ("GFS Model", "AVNO"),
    ("GFS Model (Interpolated 06 hours)", "AVNI"),
    ("GFS Model (Interpolated 12 hours)", "AVN2"),
    ("GFS Model 10-day tracker", "AVXO"),
    ("GFS Model 10-day tracker (Interpolated 06 hours)", "AVXI"),
    ("GFS Model 10-day tracker (Interpolated 12 hours)", "AVX2"),
    ("GFS Model (Interpolated 06 hrs) variable offset - intensity/radii", "AHNI"),
    ("GFS Model (Interpolated 12 hrs) variable offset - intensity/radii", "AHN2"),
    ("GFS Ensemble control member", "AC00"),
    ("GFS Ensemble +01 member", "AP01"),
    ("GFS Ensemble +02 member", "AP02"),
    ("GFS Ensemble +03 member", "AP03"),
    ("GFS Ensemble +04 member", "AP04"),
    ("GFS Ensemble +05 member", "AP05"),
    ("GFS Ensemble +06 member", "AP06"),
    ("GFS Ensemble +07 member", "AP07"),
    ("GFS Ensemble +08 member", "AP08"),
    ("GFS Ensemble +09 member", "AP09"),
    ("GFS Ensemble +10 member", "AP10"),
    ("GFS Ensemble +11 member", "AP11"),
    ("GFS Ensemble +12 member", "AP12"),
    ("GFS Ensemble +13 member", "AP13"),
    ("GFS Ensemble +14 member", "AP14"),
    ("GFS Ensemble +15 member", "AP15"),
    ("GFS Ensemble +16 member", "AP16"),
    ("GFS Ensemble +17 member", "AP17"),
    ("GFS Ensemble +18 member", "AP18"),
    ("GFS Ensemble +19 member", "AP19"),
    ("GFS Ensemble +20 member", "AP20"),
    ("GFS Ensemble +21 member", "AP21"),
    ("GFS Ensemble +22 member", "AP22"),
    ("GFS Ensemble +23 member", "AP23"),
    ("GFS Ensemble +24 member", "AP24"),
    ("GFS Ensemble +25 member", "AP25"),
    ("GFS Ensemble +26 member", "AP26"),
    ("GFS Ensemble +27 member", "AP27"),
    ("GFS Ensemble +28 member", "AP28"),
    ("GFS Ensemble +29 member", "AP29"),
    ("GFS Ensemble +30 member", "AP30"),
    ("GFS Ensemble Mean", "AEMN"),
    ("GFS Ensemble Mean (Interpolated 06 hours)", "AEMI"),
    ("GFS Ensemble Mean (Interpolated 12 hours)", "AEM2"),
    ("GFS New Ensemble Mean", "AMMN"),
    ("Experimental NCEP FV3 Global Model (2018)", "PRFV"),
    ("Experimental NCEP FV3 Global Model (Interpolated 06 hrs) (2018)", "PRVI"),
    ("Experimental NCEP FV3 Global Model (Interpolated 12 hrs) (2018)", "PRV2"),
    ("UKMET model (Developmental)", "UKM"),
    ("UKMET model (Interpolated 06 hours)", "UKMI"),
    ("UKMET model (Interpolated 12 hours)", "UKM2"),
    ("UKMET model GTS (Official)", "EGRR"),
    ("UKMET model GTS (Official - Interpolated 06 hours)", "EGRI"),
    ("UKMET model GTS (Official - Interpolated 12 hours)", "EGR2"),
    ("UKMET model GTS (2014 test)", "KEGR"),
    ("UKMET model GTS (2014 test - Interpolated 06 hours)", "KEGI"),
    ("UKMET model GTS (2014 test - Interpolated 12 hours)", "KEG2"),
    ("UKMET [GFS tracker]", "UKX"),
    ("UKMET [GFS tracker] (Interpolated 06 hours)", "UKXI"),
    ("UKMET [GFS tracker] (Interpolated 12 hours)", "UKX2"),
    ("NOGAPS model", "NGPS"),
    ("NOGAPS model (Interpolated 06 hours)", "NGPI"),
    ("NOGAPS model (Interpolated 12 hours)", "NGP2"),
    ("NAVGEM model", "NVGM"),
    ("NAVGEM model (Interpolated 06 hours)", "NVGI"),
    ("NAVGEM model (Interpolated 12 hours)", "NVG2"),
    ("NAVGEM/NOGAPS [GFS tracker]", "NGX"),
    ("NAVGEM/NOGAPS [GFS tracker] (Interpolated 06 hours)", "NGXI"),
    ("NAVGEM/NOGAPS [GFS tracker] (Interpolated 12 hours)", "NGX2"),
    ("Canadian model", "CMC"),
    ("Canadian model (Interpolated 06 hours)", "CMCI"),
    ("Canadian Model (Interpolated 12 hours)", "CMC2"),
    ("Canadian model Ensemble Mean", "CEMN"),
    ("Canadian model Ensemble Mean (Interpolated 06 hours)", "CEMI"),
    ("Canadian model Ensemble Mean (Interpolated 12 hours)", "CEM2"),
    ("Canadian model Ensemble control", "CC00"),
    ("Canadian model Ensemble +01 member", "CP01"),
    ("Canadian model Ensemble +02 member", "CP02"),
    ("Canadian model Ensemble +03 member", "CP03"),
    ("Canadian model Ensemble +04 member", "CP04"),
    ("Canadian model Ensemble +05 member", "CP05"),
    ("Canadian model Ensemble +06 member", "CP06"),
    ("Canadian model Ensemble +07 member", "CP07"),
    ("Canadian model Ensemble +08 member", "CP08"),
    ("Canadian model Ensemble +09 member", "CP09"),
    ("Canadian model Ensemble +10 member", "CP10"),
    ("Canadian model Ensemble +11 member", "CP11"),
    ("Canadian model Ensemble +12 member", "CP12"),
    ("Canadian model Ensemble +13 member", "CP13"),
    ("Canadian model Ensemble +14 member", "CP14"),
    ("Canadian model Ensemble +15 member", "CP15"),
    ("Canadian model Ensemble +16 member", "CP16"),
    ("Canadian model Ensemble +17 member", "CP17"),
    ("Canadian model Ensemble +18 member", "CP18"),
    ("Canadian model Ensemble +19 member", "CP19"),
    ("Canadian model Ensemble +20 member", "CP20"),
    ("ECMWF model", "ECM"),
    ("ECMWF model (Interpolated 06 hours)", "ECMI"),
    ("ECMWF model (Interpolated 12 hours)", "ECM2"),
    ("ECMWF model [NCEP tracker]", "EMX"),
    ("ECMWF model [NCEP tracker] (Interpolated 06 hrs)", "EMXI"),
    ("ECMWF model [NCEP tracker] (Interpolated 12 hrs)", "EMX2"),
    ("ECMWF model [HCCA tracker]", "EMH"),
    ("ECMWF model [HCCA tracker] (Interpolated 06 hrs)", "EMHI"),
    ("ECMWF model [HCCA tracker] (Interpolated 12 hrs)", "EMH2"),
    ("ECMWF model [HCCA tracker] (Interpolated 06 hrs) - variable offset radii", "EHHI"),
    ("ECMWF model [HCCA tracker] (Interpolated 12 hrs) - variable offset radii", "EHH2"),
    ("ECMWF model Ensemble Mean [NCEP tracker]", "EEMN"),
    ("ECMWF model Ensemble Mean [NCEP tracker] (Interpolated 06 hours)", "EMNI"),
    ("ECMWF model Ensemble Mean [NCEP tracker] (Interpolated 12 hours)", "EMN2"),
    ("ECMWF model Ensemble Mean [NCEP tracker] (Interpolated 18 hours)", "EMN3"),
    ("ECMWF model Ensemble Mean [NCEP tracker] (Interpolated 24 hours)", "EMN4"),
    ("ECMWF model Ensemble control member [NCEP tracker]", "EC00"),
    ("ECMWF model Ensemble +01 member [NCEP tracker]", "EN01"),
    ("ECMWF model Ensemble +02 member [NCEP tracker]", "EN02"),
    ("ECMWF model Ensemble +03 member [NCEP tracker]", "EN03"),
    ("ECMWF model Ensemble +04 member [NCEP tracker]", "EN04"),
    ("ECMWF model Ensemble +05 member [NCEP tracker]", "EN05"),
    ("ECMWF model Ensemble +06 member [NCEP tracker]", "EN06"),
    ("ECMWF model Ensemble +07 member [NCEP tracker]", "EN07"),
    ("ECMWF model Ensemble +08 member [NCEP tracker]", "EN08"),
    ("ECMWF model Ensemble +09 member [NCEP tracker]", "EN09"),
    ("ECMWF model Ensemble +10 member [NCEP tracker]", "EN10"),
    ("ECMWF model Ensemble +11 member [NCEP tracker]", "EN11"),
    ("ECMWF model Ensemble +12 member [NCEP tracker]", "EN12"),
    ("ECMWF model Ensemble +13 member [NCEP tracker]", "EN13"),
    ("ECMWF model Ensemble +14 member [NCEP tracker]", "EN14"),
    ("ECMWF model Ensemble +15 member [NCEP tracker]", "EN15"),
    ("ECMWF model Ensemble +16 member [NCEP tracker]", "EN16"),
    ("ECMWF model Ensemble +17 member [NCEP tracker]", "EN17"),
    ("ECMWF model Ensemble +18 member [NCEP tracker]", "EN18"),
    ("ECMWF model Ensemble +19 member [NCEP tracker]", "EN19"),
    ("ECMWF model Ensemble +20 member [NCEP tracker]", "EN20"),
    ("ECMWF model Ensemble +21 member [NCEP tracker]", "EN21"),
    ("ECMWF model Ensemble +22 member [NCEP tracker]", "EN22"),
    ("ECMWF model Ensemble +23 member [NCEP tracker]", "EN23"),
    ("ECMWF model Ensemble +24 member [NCEP tracker]", "EN24"),
    ("ECMWF model Ensemble +25 member [NCEP tracker]", "EN25"),
    ("ECMWF model Ensemble +26 member [NCEP tracker]", "EP01"),
    ("ECMWF model Ensemble +27 member [NCEP tracker]", "EP02"),
    ("ECMWF model Ensemble +28 member [NCEP tracker]", "EP03"),
    ("ECMWF model Ensemble +29 member [NCEP tracker]", "EP04"),
    ("ECMWF model Ensemble +30 member [NCEP tracker]", "EP05"),
    ("ECMWF model Ensemble +31 member [NCEP tracker]", "EP06"),
    ("ECMWF model Ensemble +32 member [NCEP tracker]", "EP07"),
    ("ECMWF model Ensemble +33 member [NCEP tracker]", "EP08"),
    ("ECMWF model Ensemble +34 member [NCEP tracker]", "EP09"),
    ("ECMWF model Ensemble +35 member [NCEP tracker]", "EP10"),
    ("ECMWF model Ensemble +36 member [NCEP tracker]", "EP11"),
    ("ECMWF model Ensemble +37 member [NCEP tracker]", "EP12"),
    ("ECMWF model Ensemble +38 member [NCEP tracker]", "EP13"),
    ("ECMWF model Ensemble +39 member [NCEP tracker]", "EP14"),
    ("ECMWF model Ensemble +40 member [NCEP tracker]", "EP15"),
    ("ECMWF model Ensemble +41 member [NCEP tracker]", "EP16"),
    ("ECMWF model Ensemble +42 member [NCEP tracker]", "EP17"),
    ("ECMWF model Ensemble +43 member [NCEP tracker]", "EP18"),
    ("ECMWF model Ensemble +44 member [NCEP tracker]", "EP19"),
    ("ECMWF model Ensemble +45 member [NCEP tracker]", "EP20"),
    ("ECMWF model Ensemble +46 member [NCEP tracker]", "EP21"),
    ("ECMWF model Ensemble +47 member [NCEP tracker]", "EP22"),
    ("ECMWF model Ensemble +48 member [NCEP tracker]", "EP23"),
    ("ECMWF model Ensemble +49 member [NCEP tracker]", "EP24"),
    ("ECMWF model Ensemble +50 member [NCEP tracker]", "EP25"),
    ("ECMWF model [GTS tracker]", "ECMO"),
    ("ECMWF model [GTS tracker] (Interpolated 06 hours)", "ECOI"),
    ("ECMWF model [GTS tracker] (Interpolated 12 hours)", "ECO2"),
    ("ECMWF model Ensemble Control Member [GTS tracker]", "ECME"),
    ("ECMWF model Ensemble +01 member [GTS tracker]", "EE01"),
    ("ECMWF model Ensemble +02 member [GTS tracker]", "EE02"),
    ("ECMWF model Ensemble +03 member [GTS tracker]", "EE03"),
    ("ECMWF model Ensemble +04 member [GTS tracker]", "EE04"),
    ("ECMWF model Ensemble +05 member [GTS tracker]", "EE05"),
    ("ECMWF model Ensemble +06 member [GTS tracker]", "EE06"),
    ("ECMWF model Ensemble +07 member [GTS tracker]", "EE07"),
    ("ECMWF model Ensemble +08 member [GTS tracker]", "EE08"),
    ("ECMWF model Ensemble +09 member [GTS tracker]", "EE09"),
    ("ECMWF model Ensemble +10 member [GTS tracker]", "EE10"),
    ("ECMWF model Ensemble +11 member [GTS tracker]", "EE11"),
    ("ECMWF model Ensemble +12 member [GTS tracker]", "EE12"),
    ("ECMWF model Ensemble +13 member [GTS tracker]", "EE13"),
    ("ECMWF model Ensemble +14 member [GTS tracker]", "EE14"),
    ("ECMWF model Ensemble +15 member [GTS tracker]", "EE15"),
    ("ECMWF model Ensemble +16 member [GTS tracker]", "EE16"),
    ("ECMWF model Ensemble +17 member [GTS tracker]", "EE17"),
    ("ECMWF model Ensemble +18 member [GTS tracker]", "EE18"),
    ("ECMWF model Ensemble +19 member [GTS tracker]", "EE19"),
    ("ECMWF model Ensemble +20 member [GTS tracker]", "EE20"),
    ("ECMWF model Ensemble +21 member [GTS tracker]", "EE21"),
    ("ECMWF model Ensemble +22 member [GTS tracker]", "EE22"),
    ("ECMWF model Ensemble +23 member [GTS tracker]", "EE23"),
    ("ECMWF model Ensemble +24 member [GTS tracker]", "EE24"),
    ("ECMWF model Ensemble +25 member [GTS tracker]", "EE25"),
    ("ECMWF model Ensemble +26 member [GTS tracker]", "EE26"),
    ("ECMWF model Ensemble +27 member [GTS tracker]", "EE27"),
    ("ECMWF model Ensemble +28 member [GTS tracker]", "EE29"),
    ("ECMWF model Ensemble +29 member [GTS tracker]", "EE29"),
    ("ECMWF model Ensemble +30 member [GTS tracker]", "EE30"),
    ("ECMWF model Ensemble +31 member [GTS tracker]", "EE31"),
    ("ECMWF model Ensemble +32 member [GTS tracker]", "EE32"),
    ("ECMWF model Ensemble +33 member [GTS tracker]", "EE33"),
    ("ECMWF model Ensemble +34 member [GTS tracker]", "EE34"),
    ("ECMWF model Ensemble +35 member [GTS tracker]", "EE35"),
    ("ECMWF model Ensemble +36 member [GTS tracker]", "EE36"),
    ("ECMWF model Ensemble +37 member [GTS tracker]", "EE37"),
    ("ECMWF model Ensemble +38 member [GTS tracker]", "EE38"),
    ("ECMWF model Ensemble +39 member [GTS tracker]", "EE39"),
    ("ECMWF model Ensemble +40 member [GTS tracker]", "EE40"),
    ("ECMWF model Ensemble +41 member [GTS tracker]", "EE41"),
    ("ECMWF model Ensemble +42 member [GTS tracker]", "EE42"),
    ("ECMWF model Ensemble +43 member [GTS tracker]", "EE43"),
    ("ECMWF model Ensemble +44 member [GTS tracker]", "EE44"),
    ("ECMWF model Ensemble +45 member [GTS tracker]", "EE45"),
    ("ECMWF model Ensemble +46 member [GTS tracker]", "EE46"),
    ("ECMWF model Ensemble +47 member [GTS tracker]", "EE47"),
    ("ECMWF model Ensemble +48 member [GTS tracker]", "EE48"),
    ("ECMWF model Ensemble +49 member [GTS tracker]", "EE49"),
    ("ECMWF model Ensemble +50 member [GTS tracker]", "EE50"),
    ("Japanese Global Spectral Model", "JGSM"),
    ("Japanese Global Spectral Model (Interpolated 06 hours)", "JGSI"),
    ("Japanese Global Spectral Model (Interpolated 12 hours)", "JGS2"),
    ("NHC Multi-Model Consensus (Retired)", "CONU"),
    ("Consensus of all: AVNI/GHMI/EGRI/NGPI", "GUNA"),
    ("Corrected version of GUNA", "CGUN"),
    ("Consensus of all: AVNI/EGRI/HWFI (2018 version)", "TCON"),
    ("Consensus of all: AVNI/EGRI/HWFI (2018 version)", "TCOE"),
    ("Consensus of all: AVNI/EGRI/HWFI (2018 version)", "TCOA"),
    ("Corrected version of TCON", "TCCN"),
    ("Consensus of all: DSHP/LGEM/HWFI (2018 version)", "ICON"),
    ("Consensus of >=2: AVNI/EGRI/HWFI/EMXI/CTCI/EMNI (2019 version)", "TVCN"),
    ("Consensus of >=2: AVNI/EGRI/HWFI/EMXI/CTCI/HMNI/EMNI (2019 version)", "TVCE"),
    ("Consensus of >=2: AVNI/EGRI/HWFI/EMXI/CTCI/EMNI (2019 version)", "TVCA"),
    ("Consensus of >=2: AVNIx2/EGRIx2/HWFI/EMXIx2/CTCI (2018 version)", "TVDG"),
    ("Corrected version of TVCN", "TVCC"),
    ("Consensus of >=2: AVNI/EGRI/GHMI/HWFI/CTCI (2016 version)", "TVCP"),
    ("Consensus of AVNI and EMXI", "GFEX"),
    ("Consensus of >=2: AVNI/EGRI/HWFI/EMXIx2/CTCI (2018 version)", "TVCX"),
    ("Consensus of >=2: AVNIx2/EGRI/HWFI/EMXIx2/CTCI (2018 version)", "TVCY"),
    ("Consensus of >=2: DSHP/LGEM/HWFI/CTCI/HMNI (2018 version)", "IVCN"),
    ("Consensus of >=2: DSHP/LGEM/HWFI/CTCI/HMNI (2018 version)", "IVCX"),
    ("Consensus of >=2: DSHP/LGEM/HWFIx2/CTCIx2/HMNIx2 (2018 version)", "IVDR"),
    ("Consensus of >=2: DSHP/LGEM/HWFI/RI??+CTCI", "IVCR"),
    ("Forecaster Created Consensus Guidance (any model combination)", "RYOC"),
    ("Forecaster Created Consensus Guidance (any model combination)", "MYOC"),
    ("SHIFOR intensity model 3-day", "SHFR"),
    ("SHIFOR intensity model 5-day", "SHF5"),
    ("SHIPS model", "SHIP"),
    ("Decay SHIPS model", "DSHP"),
    ("SHIPS Logistic Growth Equation (LGE) forecast model", "LGEM"),
    ("SHIPS model (ECMWF)", "SHPE"),
    ("Decay SHIPS model (ECMWF)", "DSPE"),
    ("SHIPS Logistic Growth Equation (LGE) forecast model (ECMWF)", "LGME"),
    ("Neural Net Intensity Consensus (Bias Corrected)", "NNIC"),
    ("Neural Net Intensity Consensus (Uncorrected)", "NNIB"),
    ("SHIPS model parallel (experimental - do not use)", "SHPP"),
    ("Decay SHIPS model parallel (experimental - do not use)", "DSPP"),
    ("Rapid Intensity Aid 25kts (24 hr RI Prob)", "RI25"),
    ("Rapid Intensity Aid 30kts (24 hr RI Prob)", "RI30"),
    ("Rapid Intensity Aid 35kts (24 hr RI Prob)", "RI35"),
    ("Rapid Intensity Aid 40kts (24 hr RI Prob)", "RI40"),
    ("McAdie Radii CLIPER model", "MRCL"),
    ("McAdie Radii CLIPER model (Interpolated)", "MRCI"),
    ("DeMaria Radii CLIPER model", "DRCL"),
    ("DeMaria Radii CLIPER model (Interpolated)", "DRCI"),
    ("Wind Radii Consensus of >=2: AVHI/EMXI/HHFI/ (2017 version)", "RVCN"),
    ("SUNY Advanced Hurricane WRF", "AHW4"),
    ("SUNY Advanced Hurricane WRF (Interpolated 06 hours)", "AHWI"),
    ("SUNY Advanced Hurricane WRF (Interpolated 12 hours)", "AHW2"),
    ("NRL COAMPS-TC model", "COTC"),
    ("NRL COAMPS-TC model (Interpolated 06 hours)", "COTI"),
    ("NRL COAMPS-TC model (Interpolated 12 hours)", "COT2"),
    ("NRL COAMPS-TC model experimental version", "CTCX"),
    ("NRL COAMPS-TC expt (Interpolated 06 hours) - variable offset intensity", "CTCI"),
    ("NRL COAMPS-TC expt (Interpolated 12 hours) - variable offset intensity", "CTC2"),
    ("NRL COAMPS-TC expt (Interpolated 06 hours) - variable offset radii", "CHCI"),
    ("NRL COAMPS-TC expt (Interpolated 12 hours) - variable offset radii", "CHC2"),
    ("PSU ARW w/Doppler 2011 version", "A4PS"),
    ("PSU ARW w/Doppler 2011 version (Interpolated 06 hours)", "A4PI"),
    ("PSU ARW w/Doppler 2011 version (Interpolated 12 hours)", "A4P2"),
    ("PSU ARW", "APSU"),
    ("PSU ARW (Interpolated 06 hours)", "APSI"),
    ("PSU ARW (Interpolated 12 hours)", "APS2"),
    ("ESRL FIM 2011 version", "FIMY"),
    ("ESRL FIM 2011 version (Interpolated 06 hours)", "FIMI"),
    ("ESRL FIM 2011 version (Interpolated 12 hours)", "FIM2"),
    ("ESRL FIM", "FIM9"),
    ("ESRL FIM (Interpolated 06 hours)", "FM9I"),
    ("ESRL FIM (Interpolated 12 hours)", "FM92"),
    ("UW-NMS 8km model", "UWN8"),
    ("UW-NMS 8km model (Interpolated 06 hours)", "UWNI"),
    ("UW-NMS 8km model (Interpolated 12 hours)", "UWN2"),
    ("UW-NMS 4km model", "UWN4"),
    ("UW-NMS 4km model (Interpolated 06 hours)", "UW4I"),
    ("UW-NMS 4km model (Interpolated 12 hours)", "UW42"),
    ("NCEP/AOML HWRF 3km model", "H3GP"),
    ("NCEP/AOML HWRF 3km (Interpolated 06 hours)", "H3GI"),
    ("NCEP/AOML HWRF 3km (Interpolated 12 hours)", "H3G2"),
    ("CSU-CIRA SPICE statistical intensity consensus", "SPC3"),
    ("HFIP track consensus of >=2: AVNI/EGRI/HWFI/EMXI/GPMI (2014 version)", "TV15"),
    ("HFIP intensity consensus of >=2: DSHP/LGEM/HWFI/GPMI/CXTI/UW4I (2014 version)", "IV15"),
    ("GFDL Ensemble Mean", "GPMN"),
    ("GFDL Ensemble Mean (Interpolated 06 hours)", "GPMI"),
    ("GFDL Ensemble Mean (Interpolated 12 hours)", "GPM2"),
    ("GFDL Ensemble +00 Control", "GP00"),
    ("GFDL Ensemble +00 Control (Interpolated 06 hours)", "G00I"),
    ("GFDL Ensemble +00 Control (Interpolated 12 hours)", "G002"),
    ("GFDL Ensemble +01 member (unbogussed)", "GP01"),
    ("GFDL Ensemble +01 member (unbogussed) (Interpolated 06 hours)", "G01I"),
    ("GFDL Ensemble +01 member (unbogussed) (Interpolated 12 hours)", "G012"),
    ("GFDL Ensemble +02 member", "GP02"),
    ("GFDL Ensemble +02 member (Interpolated 06 hours)", "G02I"),
    ("GFDL Ensemble +02 member (Interpolated 12 hours)", "G022"),
    ("GFDL Ensemble +03 member", "GP03"),
    ("GFDL Ensemble +03 member (Interpolated 06 hours)", "G03I"),
    ("GFDL Ensemble +03 member (Interpolated 12 hours)", "G032"),
    ("GFDL Ensemble +04 member", "GP04"),
    ("GFDL Ensemble +04 member (Interpolated 06 hours)", "G04I"),
    ("GFDL Ensemble +04 member (Interpolated 12 hours)", "G042"),
    ("GFDL Ensemble +05 member", "GP05"),
    ("GFDL Ensemble +05 member (Interpolated 06 hours)", "G05I"),
    ("GFDL Ensemble +05 member (Interpolated 12 hours)", "G052"),
    ("GFDL Ensemble +06 member", "GP06"),
    ("GFDL Ensemble +06 member (Interpolated 06 hours)", "G06I"),
    ("GFDL Ensemble +06 member (Interpolated 12 hours)", "G062"),
    ("GFDL Ensemble +07 member", "GP07"),
    ("GFDL Ensemble +07 member (Interpolated 06 hours)", "G07I"),
    ("GFDL Ensemble +07 member (Interpolated 12 hours)", "G072"),
    ("GFDL Ensemble +08 member", "GP08"),
    ("GFDL Ensemble +08 member (Interpolated 06 hours)", "G08I"),
    ("GFDL Ensemble +08 member (Interpolated 12 hours)", "G082"),
    ("GFDL Ensemble +09 member", "GP09"),
    ("GFDL Ensemble +09 member (Interpolated 06 hours)", "G09I"),
    ("GFDL Ensemble +09 member (Interpolated 12 hours)", "G092"),
    ("GFDL Ensemble +10 member", "GP10"),
    ("GFDL Ensemble +10 member (Interpolated 06 hours)", "G10I"),
    ("GFDL Ensemble +10 member (Interpolated 12 hours)", "G102"),
    ("GFDL Ensemble +11 member", "GP11"),
    ("GFDL Ensemble +11 member (Interpolated 06 hours)", "G11I"),
    ("GFDL Ensemble +11 member (Interpolated 12 hours)", "G112"),
    ("GFDL Ensemble +12 member", "GP12"),
    ("GFDL Ensemble +12 member (Interpolated 06 hours)", "G12I"),
    ("GFDL Ensemble +12 member (Interpolated 12 hours)", "G122"),
    ("GFDL Ensemble +13 member", "GP13"),
    ("GFDL Ensemble +13 member (Interpolated 06 hours)", "G13I"),
    ("GFDL Ensemble +13 member (Interpolated 12 hours)", "G132"),
    ("GFDL Ensemble +14 member", "GP14"),
    ("GFDL Ensemble +14 member (Interpolated 06 hours)", "G14I"),
    ("GFDL Ensemble +14 member (Interpolated 12 hours)", "G142"),
    ("GFDL Ensemble +15 member", "GP15"),
    ("GFDL Ensemble +15 member (Interpolated 06 hours)", "G15I"),
    ("GFDL Ensemble +15 member (Interpolated 12 hours)", "G152"),
    ("GFDL Ensemble +16 member", "GP16"),
    ("GFDL Ensemble +16 member (Interpolated 06 hours)", "G16I"),
    ("GFDL Ensemble +16 member (Interpolated 12 hours)", "G162"),
    ("GFDL Ensemble +17 member", "GP17"),
    ("GFDL Ensemble +17 member (Interpolated 06 hours)", "G17I"),
    ("GFDL Ensemble +17 member (Interpolated 12 hours)", "G172"),
    ("HWRF Ensemble Mean", "HWMN"),
    ("HWRF Ensemble Mean (Interpolated 06 hours)", "HWMI"),
    ("HWRF Ensemble Mean (Interpolated 12 hours)", "HWM2"),
    ("Consensus of 5: DHSP/LGEM/HHFI/CHTI+RI40 or RI35 or RI30 or RI25", "IVRI"),
    ("Extrapolation using past 12-hr motion (NHC-NCO PARA)", "KXTR"),
    ("CLImatology-PERsistence model 3-day (NHC-NCO PARA)", "KCLP"),
    ("CLImatology-PERsistence model 5-day (NHC-NCO PARA)", "KCL5"),
    ("LBAR (NHC-NCO PARA)", "KLBR"),
    ("Combination of CLP5 and Decay-SHIFOR run on operational inputs (NHC-NCO PARA)", "KOCD"),
    ("SHIFOR intensity model 3-day (NHC-NCO PARA)", "KSFR"),
    ("SHIFOR intensity model 5-day (NHC-NCO PARA)", "KSF5"),
    ("SHIPS model (NHC-NCO PARA)", "KSHP"),
    ("Decay SHIPS model (NHC-NCO PARA)", "KDSP"),
    ("SHIPS Logistic Growth Equation (LGE) forecast model (NHC-NCO PARA)", "KLGM"),
    ("HFIP Corrected Consensus Approach model", "HCCA"),
    ("UKMET MOGREPS-G Ensemble Control Member", "UE00"),
    ("UKMET MOGREPS-G Ensemble +01 member", "UE01"),
    ("UKMET MOGREPS-G Ensemble +02 member", "UE02"),
    ("UKMET MOGREPS-G Ensemble +03 member", "UE03"),
    ("UKMET MOGREPS-G Ensemble +04 member", "UE04"),
    ("UKMET MOGREPS-G Ensemble +05 member", "UE05"),
    ("UKMET MOGREPS-G Ensemble +06 member", "UE06"),
    ("UKMET MOGREPS-G Ensemble +07 member", "UE07"),
    ("UKMET MOGREPS-G Ensemble +08 member", "UE08"),
    ("UKMET MOGREPS-G Ensemble +09 member", "UE09"),
    ("UKMET MOGREPS-G Ensemble +10 member", "UE10"),
    ("UKMET MOGREPS-G Ensemble +11 member", "UE11"),
    ("UKMET MOGREPS-G Ensemble +12 member", "UE12"),
    ("UKMET MOGREPS-G Ensemble +13 member", "UE13"),
    ("UKMET MOGREPS-G Ensemble +14 member", "UE14"),
    ("UKMET MOGREPS-G Ensemble +15 member", "UE15"),
    ("UKMET MOGREPS-G Ensemble +16 member", "UE16"),
    ("UKMET MOGREPS-G Ensemble +17 member", "UE17"),
    ("UKMET MOGREPS-G Ensemble +18 member", "UE18"),
    ("UKMET MOGREPS-G Ensemble +19 member", "UE19"),
    ("UKMET MOGREPS-G Ensemble +20 member", "UE20"),
    ("UKMET MOGREPS-G Ensemble +21 member", "UE21"),
    ("UKMET MOGREPS-G Ensemble +22 member", "UE22"),
    ("UKMET MOGREPS-G Ensemble +23 member", "UE23"),
    ("UKMET MOGREPS-G Ensemble +24 member", "UE24"),
    ("UKMET MOGREPS-G Ensemble +25 member", "UE25"),
    ("UKMET MOGREPS-G Ensemble +26 member", "UE26"),
    ("UKMET MOGREPS-G Ensemble +27 member", "UE27"),
    ("UKMET MOGREPS-G Ensemble +28 member", "UE28"),
    ("UKMET MOGREPS-G Ensemble +29 member", "UE29"),
    ("UKMET MOGREPS-G Ensemble +30 member", "UE30"),
    ("UKMET MOGREPS-G Ensemble +31 member", "UE31"),
    ("UKMET MOGREPS-G Ensemble +32 member", "UE32"),
    ("UKMET MOGREPS-G Ensemble +32 member", "UE33"),
    ("UKMET MOGREPS-G Ensemble +34 member", "UE34"),
    ("UKMET MOGREPS-G Ensemble Previous Control member", "UE35"),
    ("UKMET MOGREPS-G Ensemble Mean", "UEMN"),
    ("UKMET MOGREPS-G Ensemble Mean (Interpolated 06 hours)", "UEMI"),
    ("UKMET MOGREPS-G Ensemble Mean (Interpolated 12 hours)", "UEM2"),
    ("CFAN-Calibrated ECMWF", "ECMWFC"),
    ("CFAN ECMWF", "ECMWFR"),
    ("CFAN-Calibrated GFS/GEFS", "NCEPC"),
    ("CFAN Raw GFS/GEFS", "NCEPR"),
    ("ECMWF BUFR", "ECMWFB");