INSERT INTO models (long_name, short_name)
VALUES
    ("Combined ARQ Position", "CARQ"),
    ("NHC official forecast", "OFCL"),
    ("NHC provisional forecast", "OFCP"),
    ("WPC official forecast", "OHPC"),
    ("OPC official forecast", "OOPC"),
    ("JTWC official forecast", "JTWC"),
    ("JTWC official forecast (Interpolated 06 hours)", "JTWI"),
    ("CLImatology-PERsistence model 3-day", "CLIP"),
    ("CLImatology-PERsistence model 5-day", "CLP5"),
    ("Trajectory CLIPER model 7-day", "TCLP"),
    ("HWRF model", "HWRF"),
    ("HWRF w/ ECMWF fields model", "HWFE"),
    ("HWRF model [2013 version]", "HW3F"),
    ("HMON model", "HMON"),
    ("Coupled Hurricane Intensity Prediction System", "CHIP"),
    ("HAFS-A - Stand Alone Regional", "HAFA"),
    ("HAFS-B - Global with Static Nest", "HAFB"),
    ("HAFS-SAR with ESG Grid", "HAFJ"),
    ("Basin-Scale HWRF", "HB20"),
    ("GFDL model", "GFDL"),
    ("Parallel version of GFDL", "GFD5"),
    ("GFDL w/ ECMWF fields model", "GFDE"),
    ("GFDL using [NCEP tracker]", "GFDT"),
    ("Navy GFDL model", "GFDN"),
    ("NAM model", "NAM"),
    ("GFS Model", "AVNO"),
    ("GFS Model (Interpolated 06 hours)", "AVNI"),
    ("GFS Model (Interpolated 12 hours)", "AVN2"),
    ("GFS Ensemble control member", "AC00"),
    ("GFS Ensemble +01 member", "AP01"),
    ("GFS Ensemble +02 member", "AP02"),
    ("GFS Ensemble +03 member", "AP03"),
    ("GFS Ensemble +04 member", "AP04"),
    ("GFS Ensemble +05 member", "AP05"),
    ("GFS Ensemble +06 member", "AP06"),
    ("GFS Ensemble +07 member", "AP07"),
    ("GFS Ensemble +08 member", "AP08"),
    ("GFS Ensemble +09 member", "AP09"),
    ("GFS Ensemble +10 member", "AP10"),
    ("GFS Ensemble +11 member", "AP11"),
    ("GFS Ensemble +12 member", "AP12"),
    ("GFS Ensemble +13 member", "AP13"),
    ("GFS Ensemble +14 member", "AP14"),
    ("GFS Ensemble +15 member", "AP15"),
    ("GFS Ensemble +16 member", "AP16"),
    ("GFS Ensemble +17 member", "AP17"),
    ("GFS Ensemble +18 member", "AP18"),
    ("GFS Ensemble +19 member", "AP19"),
    ("GFS Ensemble +20 member", "AP20"),
    ("GFS Ensemble +21 member", "AP21"),
    ("GFS Ensemble +22 member", "AP22"),
    ("GFS Ensemble +23 member", "AP23"),
    ("GFS Ensemble +24 member", "AP24"),
    ("GFS Ensemble +25 member", "AP25"),
    ("GFS Ensemble +26 member", "AP26"),
    ("GFS Ensemble +27 member", "AP27"),
    ("GFS Ensemble +28 member", "AP28"),
    ("GFS Ensemble +29 member", "AP29"),
    ("GFS Ensemble +30 member", "AP30"),
    ("GFS Ensemble Mean", "AEMN"),
    ("GFS Ensemble Mean (Interpolated 06 hours)", "AEMI"),
    ("GFS Ensemble Mean (Interpolated 12 hours)", "AEM2"),
    ("GFS New Ensemble Mean", "AMMN"),
    ("UKMET model (Developmental)", "UKM"),
    ("UKMET model GTS (Official)", "EGRR"),
    ("UKMET [GFS tracker]", "UKX"),
    ("Canadian model", "CMC"),
    ("Canadian model Ensemble Mean", "CEMN"),
    ("Canadian model Ensemble control", "CC00"),
    ("Canadian model Ensemble +01 member", "CP01"),
    ("Canadian model Ensemble +02 member", "CP02"),
    ("Canadian model Ensemble +03 member", "CP03"),
    ("Canadian model Ensemble +04 member", "CP04"),
    ("Canadian model Ensemble +05 member", "CP05"),
    ("Canadian model Ensemble +06 member", "CP06"),
    ("Canadian model Ensemble +07 member", "CP07"),
    ("Canadian model Ensemble +08 member", "CP08"),
    ("Canadian model Ensemble +09 member", "CP09"),
    ("Canadian model Ensemble +10 member", "CP10"),
    ("Canadian model Ensemble +11 member", "CP11"),
    ("Canadian model Ensemble +12 member", "CP12"),
    ("Canadian model Ensemble +13 member", "CP13"),
    ("Canadian model Ensemble +14 member", "CP14"),
    ("Canadian model Ensemble +15 member", "CP15"),
    ("Canadian model Ensemble +16 member", "CP16"),
    ("Canadian model Ensemble +17 member", "CP17"),
    ("Canadian model Ensemble +18 member", "CP18"),
    ("Canadian model Ensemble +19 member", "CP19"),
    ("Canadian model Ensemble +20 member", "CP20"),
    ("ECMWF model", "ECM"),
    ("ECMWF model (Interpolated 06 hours)", "ECMI"),
    ("ECMWF model (Interpolated 12 hours)", "ECM2"),
    ("ECMWF model [NCEP tracker]", "EMX"),
    ("ECMWF model [HCCA tracker]", "EMH"),
    ("ECMWF model Ensemble Mean [NCEP tracker]", "EEMN"),
    ("CFAN-Calibrated ECMWF", "ECMWFC"),
    ("CFAN ECMWF", "ECMWFR"),
    ("CFAN-Calibrated GFS/GEFS", "NCEPC"),
    ("CFAN Raw GFS/GEFS", "NCEPR"),
    ("ECMWF BUFR", "ECMWFB");